# Generated by Django 4.2.24 on 2025-09-30 21:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoplus', '0002_role_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'Rôle', 'verbose_name_plural': 'Rôles'},
        ),
        migrations.AlterField(
            model_name='role',
            name='can_manage_inventory',
            field=models.BooleanField(default=False, verbose_name="Peut gérer l'inventaire"),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_manage_orders',
            field=models.BooleanField(default=False, verbose_name='Peut gérer les commandes'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_manage_users',
            field=models.BooleanField(default=False, verbose_name='Peut gérer les utilisateurs'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_view_reports',
            field=models.BooleanField(default=False, verbose_name='Peut voir les rapports'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom du rôle'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Priorité')),
                ('category', models.CharField(choices=[('cuisine', 'Cuisine'), ('nettoyage', 'Nettoyage'), ('inventaire', 'Inventaire'), ('formation', 'Formation')], default='cuisine', max_length=20, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('estimated_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée estimée (minutes)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Complétée')),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['is_completed', 'due_date', 'priority'],
            },
        ),
    ]
