# Generated by Django 4.2.24 on 2025-09-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoplus', '0003_alter_role_options_alter_role_can_manage_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_distribute_tasks',
            field=models.BooleanField(default=False, verbose_name='Peut distribuer des tâches à tous'),
        ),
    ]
