# Generated by Django 5.2.5 on 2025-10-06 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoplus', '0008_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='jour',
            new_name='day',
        ),
    ]
