# Generated by Django 5.2.5 on 2025-10-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoplus', '0009_rename_jour_availability_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='status',
            field=models.CharField(blank=True, choices=[('en_attente', 'En attente'), ('remplie', 'Remplie'), ('validee', 'Validée')], max_length=20, null=True),
        ),
    ]
