# Generated by Django 5.2.5 on 2025-10-07 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoplus', '0010_availability_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='availability_status',
            field=models.CharField(choices=[('not_filled', 'Not filled'), ('pending', 'Pending'), ('filled', 'Filled')], default='not_filled', max_length=20),
        ),
    ]
