# Generated by Django 5.2.5 on 2025-10-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoplus', '0011_remove_availability_status_user_availability_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='availability_status',
            field=models.CharField(choices=[('non_remplie', 'Non remplie'), ('en_attente', 'En attente'), ('remplie', 'Remplie')], default='non_remplie', max_length=20, verbose_name='Statut des disponibilités'),
        ),
    ]
