# Generated by Django 5.2.5 on 2025-10-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoplus', '0012_alter_user_availability_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='availability_status',
            field=models.CharField(choices=[('not_filled', 'Non remplie'), ('pending', 'En attente'), ('filled', 'Remplie')], default='not_filled', max_length=20, verbose_name='Statut des disponibilités'),
        ),
    ]
