# Generated by Django 4.2.24 on 2025-10-22 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restoplus', '0013_alter_user_availability_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date du quart')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employé')),
            ],
        ),
        migrations.AlterField(
            model_name='availability',
            name='day',
            field=models.CharField(choices=[('monday', 'Lundi'), ('tuesday', 'Mardi'), ('wednesday', 'Mercredi'), ('thursday', 'Jeudi'), ('friday', 'Vendredi'), ('saturday', 'Samedi'), ('sunday', 'Dimanche')], max_length=10),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine_debut', models.DateField(verbose_name='Semaine débutant le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('Quarts', models.ManyToManyField(blank=True, related_name='schedules', to='restoplus.quart', verbose_name='Quarts')),
            ],
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date du quart')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('has_break', models.BooleanField(default=True, verbose_name='A une pause')),
                ('pause_duree', models.PositiveIntegerField(default=30, help_text='Durée de la pause en minutes (0-120)', verbose_name='Durée de pause (minutes)')),
                ('pause_debut', models.TimeField(blank=True, null=True, verbose_name='Début de pause')),
                ('pause_fin', models.TimeField(blank=True, null=True, verbose_name='Fin de pause')),
                ('note', models.TextField(blank=True, help_text='Informations supplémentaires sur ce quart', max_length=500, verbose_name='Note')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='draft', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Quart de travail',
                'verbose_name_plural': 'Quarts de travail',
                'ordering': ['date', 'heure_debut'],
                'indexes': [models.Index(fields=['employee', 'date'], name='restoplus_w_employe_4e8154_idx'), models.Index(fields=['date', 'status'], name='restoplus_w_date_a3f153_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
