# Generated by Django 5.2.5 on 2025-10-23 23:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoplus', '0014_alter_availability_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro invalide.Il doit être au format 444-555-1234', regex='^\\+?1?\\s*(?:\\([2-9]\\d{2}\\)|[2-9]\\d{2})[-.\\s]?\\d{3}[-.\\s]?\\d{4}$')], verbose_name='Téléphone'),
        ),
    ]
