# Generated by Django 5.2.5 on 2025-10-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoplus', '0015_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='poste',
            field=models.CharField(blank=True, max_length=100, verbose_name='Poste'),
        ),
    ]
