# Generated by Django 4.2.23 on 2025-10-29 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoplus', '0014_quart_alter_availability_day_schedule_workshift'),
        ('restoplus', '0016_user_poste'),
    ]

    operations = [
    ]
