# Generated by Django 5.2.5 on 2025-10-29 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoplus', '0017_merge_20251029_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.RegexValidator(message="Format de l'adresse e-mail invalide.", regex='^((?!\\.)[\\w\\-_.]*[^.])(@\\w+)(\\.\\w+(\\.\\w+)?[^.\\W])$')], verbose_name='Courriel'),
        ),
    ]
