# Generated by Django 5.2.8 on 2025-11-06 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoplus', '0018_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=254, validators=[django.core.validators.RegexValidator(message="Format de l'adresse courriel invalide.", regex='^((?!\\.)[\\w\\-_.]*[^.])(@\\w+)(\\.\\w+(\\.\\w+)?[^.\\W])$')], verbose_name='Courriel'),
        ),
    ]
