# Generated by Django 5.2.7 on 2025-11-15 19:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoplus', '0018_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=254, validators=[django.core.validators.RegexValidator(message="Format de l'adresse courriel invalide.", regex='^((?!\\.)[\\w\\-_.]*[^.])(@\\w+)(\\.\\w+(\\.\\w+)?[^.\\W])$')], verbose_name='Courriel'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du ticket')),
                ('description', models.TextField(verbose_name='Description du problème')),
                ('category', models.CharField(choices=[('Bris', "Bris d'équipement"), ('inventaire', "Problème d'inventaire"), ('technique', 'Problème technique'), ('autre', 'Autre')], default='autre', max_length=50, verbose_name='Catégorie')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-date_created'],
            },
        ),
    ]
