# Generated by Django 5.2.5 on 2025-11-19 03:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoplus', '0018_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('sku', models.CharField(blank=True, max_length=50, unique=True, verbose_name='SKU')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Catégorie')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantité')),
                ('unit', models.CharField(choices=[('pcs', 'Pièce'), ('lb', 'Livres'), ('g', 'Grammes'), ('l', 'Litres'), ('ml', 'Millilitres'), ('pack', 'Paquet')], default='pcs', max_length=10, verbose_name='Unité')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Fournisseur')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix coûtant')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': "Article d'inventaire",
                'verbose_name_plural': 'Inventaire',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=254, validators=[django.core.validators.RegexValidator(message="Format de l'adresse courriel invalide.", regex='^((?!\\.)[\\w\\-_.]*[^.])(@\\w+)(\\.\\w+(\\.\\w+)?[^.\\W])$')], verbose_name='Courriel'),
        ),
    ]
