# Generated by Django 5.2.8 on 2025-11-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoplus', '0019_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('code', models.CharField(max_length=6, verbose_name='Code de réinitialisation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('expires_at', models.DateTimeField(verbose_name="Date d'expiration")),
                ('is_used', models.BooleanField(default=False, verbose_name='Code utilisé')),
                ('attempts', models.IntegerField(default=0, verbose_name='Nombre de tentatives')),
            ],
            options={
                'verbose_name': 'Code de réinitialisation',
                'verbose_name_plural': 'Codes de réinitialisation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'code', 'is_used'], name='restoplus_p_email_c0fe87_idx'), models.Index(fields=['expires_at'], name='restoplus_p_expires_8b4e78_idx')],
            },
        ),
    ]
