# Generated by Django 5.2.5 on 2025-11-19 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoplus', '0019_inventory_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du ticket')),
                ('description', models.TextField(verbose_name='Description du problème')),
                ('category', models.CharField(help_text="ex: bris d'équipement, Problème d'inventaire, Problème technique, autre ...", max_length=150, verbose_name='Catégorie')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-date_created'],
            },
        ),
    ]
