# Generated by Django 5.2.7 on 2025-11-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoplus', '0019_alter_user_email_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(help_text="ex: bris d'équipement, Problème d'inventaire, Problème technique, autre ...", max_length=150, verbose_name='Catégorie'),
        ),
    ]
