# Generated by Django 5.2.5 on 2025-11-09 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoplus', '0019_inventory_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='location',
        ),
    ]
