# Generated by Django 5.2.5 on 2025-11-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoplus', '0020_remove_inventory_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pièce(tout)'), ('lb', 'Livres'), ('g', 'Grammes'), ('l', 'Litres'), ('ml', 'Millilitres'), ('pack', 'Paquet')], default='pcs', max_length=10, verbose_name='Unité'),
        ),
    ]
