# Generated by Django 5.2.7 on 2025-11-16 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoplus', '0020_remove_inventory_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de commande')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('ordered', 'Commandée'), ('received', 'Reçue'), ('cancelled', 'Annulée')], default='draft', max_length=20, verbose_name='Statut')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Fournisseur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Date de commande')),
                ('expected_delivery', models.DateField(blank=True, null=True, verbose_name='Livraison prévue')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Coût total')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_orders_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Commande de stock',
                'verbose_name_plural': 'Commandes de stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restoplus.inventory', verbose_name='Article')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restoplus.stockorder', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'verbose_name_plural': 'Articles de commande',
                'unique_together': {('order', 'inventory_item')},
            },
        ),
    ]
