# Generated by Django 5.2.7 on 2025-11-19 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoplus', '0020_alter_ticket_category'),
        ('restoplus', '0021_alter_inventory_unit'),
    ]

    operations = [
    ]
