# Generated by Django 5.2.7 on 2025-11-18 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoplus', '0021_stockorder_stockorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockorder',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='stockorder',
            name='status',
        ),
    ]
