# Generated by Django 4.2.23 on 2025-11-19 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoplus', '0020_passwordresetcode'),
        ('restoplus', '0021_alter_inventory_unit'),
    ]

    operations = [
    ]
