# Generated by Django 4.2.23 on 2025-11-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoplus', '0022_merge_20251119_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pièce'), ('lb', 'Livres'), ('g', 'Grammes'), ('l', 'Litres'), ('ml', 'Millilitres'), ('pack', 'Paquet')], default='pcs', max_length=10, verbose_name='Unité'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('task_assigned', 'Tâche assignée'), ('role_assigned', 'Rôle assigné'), ('task_completed', 'Tâche terminée'), ('reminder', 'Rappel'), ('system', 'Notification système'), ('schedule_published', 'Horaire publié')], default='system', max_length=20, verbose_name='Type de notification'),
        ),
    ]
