# Generated by Django 5.2.7 on 2025-11-18 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoplus', '0022_remove_stockorder_notes_remove_stockorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockorder',
            name='order_number',
        ),
    ]
