# Generated by Django 5.2.7 on 2025-11-19 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoplus', '0023_remove_stockorder_order_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockorderitem',
            unique_together=set(),
        ),
    ]
