# Generated by Django 5.2.5 on 2025-11-19 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoplus', '0020_passwordresetcode'),
        ('restoplus', '0022_merge_20251118_2041'),
        ('restoplus', '0024_alter_stockorderitem_unique_together'),
    ]

    operations = [
    ]
