# Generated by Django 5.2.8 on 2025-11-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoplus', '0023_alter_inventory_unit_and_more'),
        ('restoplus', '0025_merge_20251119_0050'),
    ]

    operations = [
    ]
