# Generated by Django 5.2.6 on 2025-12-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoplus', '0026_merge_20251119_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_manage_schedules',
            field=models.BooleanField(default=False, verbose_name='Peut créer les horaires'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('task_assigned', 'Tâche assignée'), ('role_assigned', 'Rôle assigné'), ('task_completed', 'Tâche terminée'), ('reminder', 'Rappel'), ('system', 'Notification système'), ('schedule_published', 'Horaire publié'), ('inventory_added', 'Inventaire ajouté')], default='system', max_length=20, verbose_name='Type de notification'),
        ),
    ]
