# Generated by Django 5.2.5 on 2025-12-06 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoplus', '0026_alter_inventory_unit'),
        ('restoplus', '0027_add_can_manage_schedules'),
    ]

    operations = [
    ]
